name: Integration tests
on: [push, pull_request]
jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      
      - name: Read node version from .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      
      - name: "Setup Node v${{ steps.nvm.outputs.NVMRC }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm install yarn
          yarn install
      
      - name: Build
        run: npm run build
      
      - name: "Run integration tests"
        run: npm run wdio:test
        env:
          CI: true
          HEADLESS: true